// Generated by HelpNDoc - http://www.helpndoc.com

unit CORHelp;

interface

const
  HELP_WelcomeToCOR = 0;
  HELP_Philosophy = 28;
  HELP_Features = 1;
  HELP_License = 2;
  HELP_Gettingstarted = 3;
  HELP_Userinterface = 7;
  HELP_Editorialmode = 8;
  HELP_Computationalmode = 9;
  HELP_HowTo = 11;
  HELP_HowtoinstallCOR = 14;
  HELP_HowtobuildCORfromthesourcecode = 15;
  HELP_HowtocheckunitsinaCellMLfile = 4;
  HELP_HowtotestaCellMLfilet = 22;
  HELP_Howtoapplyaperiodicstimulust = 23;
  HELP_Howtocreateacurrentvoltagecu = 24;
  HELP_Howtoapplyavoltageclampproto = 26;
  HELP_Howtoapplyacurrentclampproto = 25;
  HELP_FAQ = 12;
  HELP_IhavejustupdatedCORtoversion09 = 21;
  HELP_IknowCORisaWindowsprogrambutis = 5;
  HELP_IhavejustrebuiltCORyetmyversio = 16;
  HELP_Thesetupprogramlooksprettynice = 17;
  HELP_IamtryingtodebugCORfromwithinD = 18;
  HELP_DoesCORuseanythirdpartycompone = 20;
  HELP_Publications = 27;
  HELP_Contactus = 13;

implementation

end.